### import des outils

In [31]:
import pandas as pd #pour lire, manipuler, analyser, nettoyer les donnees
import numpy as np  #pour faire des calculs scientifiques
import matplotlib as plt #pour visualiser les donnees
import seaborn as sns    #pour visualiser les donnees
import scipy as scp      #prendre des decisions basées sur les lois de probabilités
import sklearn as skl    #pour creer des modeles de machine learning (regression-classification S1)

In [32]:
df=pd.read_csv("diamonds.csv")
df.head(3)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31

In [33]:
X=df[['carat', 'table', 'depth','x', 'y', 'z']]
X.head(3)

   carat  table  depth     x     y     z
0   0.23   55.0   61.5  3.95  3.98  2.43
1   0.21   61.0   59.8  3.89  3.84  2.31
2   0.23   65.0   56.9  4.05  4.07  2.31

In [34]:
Y=df['price']
Y.head(3)

0    326
1    326
2    327
Name: price, dtype: int64

### Premier Modele IA

In [35]:
from sklearn.linear_model import LinearRegression #API

In [36]:
modele=LinearRegression()  #On choisit un modele de regression
modele

LinearRegression()

In [37]:
modele.fit(X,Y)  
#on entraine le modele pour qu'il puisse trouver y_train quand l'entree est X_train

LinearRegression()

In [38]:
#Est ce que le modele s est bien entrainer
modele.score(X,Y)

0.8592186831580985

In [39]:
#Le modele est fiable en entrainement à 85.73% (precision ou R2 de 85.73%)

In [42]:
coefficients = pd.Series(
    modele.coef_,
    index=X.columns
).sort_values(key=abs, ascending=False)

coefficients

carat    10686.309081
x        -1315.667842
depth     -203.154052
table     -102.445652
y           66.321602
z           41.627697
dtype: float64

### Prediction

In [48]:
df.sample(2)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
31060,31061,0.38,Good,F,VS2,62.7,58.0,752,4.56,4.60,2.87
2654,2655,0.70,Very Good,F,VVS2,58.7,63.0,3234,5.82,5.79,3.41

In [44]:
#Faisons une prediction pour le diamant avec un carat de 0.5, table de 58 avec x=2, y=3 et z=3

In [45]:
X.head(1)

   carat  table  depth     x     y     z
0   0.23   55.0   61.5  3.95  3.98  2.43

In [46]:
new_diamant=pd.DataFrame([0.5,58,3,2,3,3]).T
new_diamant.columns=X.columns
new_diamant

   carat  table  depth    x    y    z
0    0.5   58.0    3.0  2.0  3.0  3.0

In [47]:
new_price=modele.predict(new_diamant)
new_price

array([17333.67318714])